//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privateads
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADSPR
    {
        public int id { get; set; }
        public Nullable<System.DateTime> дата_публикации { get; set; }
        public Nullable<int> id_продавца { get; set; }
        public Nullable<int> id_категории { get; set; }
        public string название_объявления { get; set; }
        public Nullable<decimal> стоимость_товара { get; set; }
        public string состояние_товара { get; set; }
        public string описание { get; set; }
        public string способ_оплаты { get; set; }
        public string способ_доставки { get; set; }
    
        public virtual Категории Категории { get; set; }
        public virtual Продавцы Продавцы { get; set; }
    }
}
